### ISSUE TITLE
SPIKE: Add OIDC support

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-sso#12]
We should consider supporting OpenID Connect (OIDC), both for inbound and outbound.

**Comment by johnbillion** [comment]
We have existing implementations for this, ie. on Ingenuity.

**Comment by rmccue** [comment]
@johnbillion Are you using the OAuth 2 plugin, or a separate one?

**Comment by johnbillion** [comment]
Sent some links to Ryan.

**Comment by rmccue** [comment]
We haven't had this requested in a while, tracking in Productboard instead.
