### ISSUE TITLE
Allow specifying different IdP name/path for each environment

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-sso#13]
Each environment (ie. dev/staging/prod) requires a separate IdP metadata file, but these all need to go into the same repo. Therefore the SSO config needs to allow a different IdP file name or path to be specified for each environment that the user sets up.

**Comment by rmccue** [comment]
You can use [environment-specific configuration](https://www.altis-dxp.com/resources/docs/getting-started/configuration/#environment-specific-configuration) for this, unless there's some other case this doesn't handle?

**Comment by johnbillion** [comment]
Correct, but the actual IdP metadata file is [hardcoded to `config/sso/saml-idp-metadata.xml`](https://github.com/humanmade/altis-sso/blob/ca8b82b777c4f5a1da713cd8d84b2ee0acdaffe9/inc/saml/namespace.php#L20-L22) so the actual IdP file that's used can't vary depending on environment.

**Comment by rmccue** [comment]
Gotcha, thanks!
