### ISSUE TITLE
Add LDAP support

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-sso#2]
We would provide this using https://github.com/clifgriffin/simple-ldap-login

- [ ] Make a PR to submit a `composer.json` and request the maintainer to publish it on packagist
- [ ] Once the above has happened require it in this package
- [ ] Add Altis configuration support for all plugin options
- [ ] Add documentation

**Comment by elodiebouneau** [comment]
@roborourke - Do you know if this has ever been requested by clients?

**Comment by rmccue** [comment]
Bumping from 4.0 for now, but moving to chores per Rob's note that this is low effort to add.

**Comment by roborourke** [comment]
Closing due to no urgent need for this and exploring alternative partnership integrations for more advanced SSO support.
