### ISSUE TITLE
Legacy file is loaded from "config" dir, not ".config"

### ISSUE THREAD

**Issue by dashaluna** [humanmade/altis-sso#24]
Per https://www.altis-dxp.com/resources/docs/getting-started/configuration/ the directory we use for config is `.config`.

The path on this line needs correcting https://github.com/humanmade/altis-sso/blob/master/inc/saml/namespace.php#L34

Acceptance criteria:

- [ ] Adding a file called `saml-idp-metadata.xml` in the `.config/sso` directory causes ***

**Comment by dashaluna** [comment]
@roborourke could you please verify this is the case and help out with the acceptance criteria regarding what should happen instead of ***.
Thank you.

**Comment by rmccue** [comment]
@dashaluna as noted in the code, this is the legacy name from older versions of Altis, and is only here for backwards compatibility. The newer versions instead use the path defined in config if it's set, or `.config/sso/saml-idp-metadata.xml`.

**Comment by dashaluna** [comment]
@rmccue oh right, thank you for explaining 👍
