### ISSUE TITLE
SPIKE: SSO framework

### ISSUE THREAD

**Issue by jennybeaumont** [humanmade/altis-sso#35]
Placeholder: looking at commonalities between SSO implementations to reduce duplication of effort

**Comment by rmccue** [comment]
Fleshing this out with some more details:

Single sign-on has a bunch of commonalities across all the potential ways you can connect. There's the protocol specific stuff (SAML, OIDC, LDAP), but there's also a lot of stuff that's basically just hooking into WordPress. The protocol specific stuff is actually usually handled by libraries anyway, and it seems like we could share this common behaviour across the protocols; it's also where things are most likely to go wrong, so sharing a common core makes it easier for us to test/etc.

The spike here is mostly around understanding what those commonalities are, how much can be shared, and the work that'd be required to actually do this. The best place to start is likely in our existing WP Simple SAML plugin.

**Comment by rmccue** [comment]
We're going to look at exploring wider support of protocols via partnerships in the short term, and continue making more incremental improvements to our SAML integration instead.
