### ISSUE TITLE
SAML validation errors on Altis Infrastructure

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/altis-sso#36]
When migrating one of the projects to Altis we came across an error in SSO module, particularly from SAML library.

```
The response was received at https://domain.com:8080/sso/verify instead of https://doman.com/sso/verify
```

My assumption was that due to some docker networking [SAML library was reading the port number incorrectly](https://github.com/onelogin/php-saml/blob/master/lib/Saml2/Utils.php#L566-L587), It was reading it 8080 but it was expected to be 443 (or 80).

To fix this we simply had to set the port to 443 explicitly from the loader - 

```
// Set server port to 443 for SAML.
if ( class_exists( '\\OneLogin\\Saml2\\Utils' ) ) {
	\OneLogin\Saml2\Utils::setSelfPort( '443' );
}
```

This issue was also reproduced locally using local testing method mentioned in the wiki here - https://github.com/humanmade/wp-simple-saml/wiki/Testing-SSO-locally
_I had to change the default port numbers to set it up locally as port 8080 is also used by Altis local-server_

(Note while debugging we first disabled the Altis SSO module to find if the problem was in any customizations in this module, but the issue still persisted so I believe the issue will also be there when using Altis SSO module as that as well uses the same plugin under the hood)

**Comment by roborourke** [comment]
cc @shadyvb - we can handle this in Altis but might be good to patch in wp-simple-saml directly
